services:
  shop-db:
    image: postgres:14-alpine
    container_name: shop-db-ct
    volumes:
      - postgres_home:/var/lib/postgresql/data/
      - ./db/migrations:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - shop-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d shop" ]
      interval: 10s
      timeout: 2s
      retries: 2

  shop-redis:
    image: bitnami/redis:7.2
    container_name: redis-ct
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - shop-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  shop-api:
    build:
      context: .
      dockerfile: shop-api/Dockerfile
    image: shop-app
    container_name: shop-app-ct
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - shop-db
      - shop-redis
    environment:
      - PAYMENTS_API_URL=http://payments-api:8081
      - PAYMENTS_API_CLIENT_ID=${PAYMENTS_API_CLIENT_ID}
      - PAYMENTS_API_CLIENT_SECRET=${PAYMENTS_API_CLIENT_SECRET}
      - PAYMENTS_API_TOKEN_URI=http://keycloak:8080/realms/shop-realm/protocol/openid-connect/token
      - SPRING_R2DBC_URL=r2dbc:postgresql://shop-db:5432/shop
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=shop-redis
      - SPRING_DATA_REDIS_PORT=6379
      - AWS_REGION=${AWS_REGION}
      - AWS_SERVICE_ENDPOINT=${AWS_SERVICE_ENDPOINT}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    networks:
      - shop-network

  payments-api:
    build:
      context: .
      dockerfile: payments-api/Dockerfile
    image: payments-app
    container_name: payments-app-ct
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - shop-api
      - keycloak
    environment:
      - PAYMENTS_API_ISSUER_URI=http://keycloak:8080/realms/shop-realm
      - SPRING_R2DBC_URL=r2dbc:postgresql://shop-db:5432/shop
      - SPRING_R2DBC_USERNAME=root
      - SPRING_R2DBC_PASSWORD=root
      - SPRING_DATA_REDIS_HOST=shop-redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - shop-network

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-ct
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./shop-realm.json:/opt/keycloak/data/import/shop-realm.json
    ports:
      - "8082:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - shop-network

volumes:
  postgres_home:
  redis_data:

networks:
  shop-network:
    driver: bridge